<a href="https://colab.research.google.com/github/rolando1102/data-science-bootcamp/blob/main/01_wprowadzenie/01_num_py_tablice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Spis** **Tresci**
  
  1.[Podstawy](https://colab.research.google.com/drive/1q9Mr3nD0nUCLhYGFuOOYLNht5AUkCU6q#scrollTo=eznGP67Iqa-a&line=1&uniqifier=1)

1.Podstawy

In [1]:
import numpy as np 
np.__version__

'1.18.5'

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

**Tablica jednowymiarowa**

In [4]:
# tablica o wymiarze 1
x= np.array([1,3])
print(x)
type(x)


[1 3]


numpy.ndarray

In [5]:
x.ndim

1

In [6]:
x.shape

(2,)

In [7]:
x.size

2

In [8]:
x.dtype

dtype('int64')

In [9]:
y = np.array([1.3,2.3,1.4])
print(y)

[1.3 2.3 1.4]


In [10]:
y.dtype

dtype('float64')

**Tablica** **dwuwymiarowa**

In [11]:
s = np.array([[1,2],[-3,1]])
print(s)

[[ 1  2]
 [-3  1]]


In [12]:
s.ndim

2

In [13]:
s.shape

(2, 2)

In [14]:
s.size

4

In [15]:
s = np.array([[1,2,4],[4,2,1]])
print(s)

[[1 2 4]
 [4 2 1]]


In [16]:
s.shape

(2, 3)

**Tablica** **trzywmiarowa**

In [17]:
x = np.array(
    [[[4,3,1],
      [3,2,1]],
     
     [[4,1,3],
      [4,2,1]],
     
     [[3,2,1],
      [4,2,4]]] 
)
print(x)

[[[4 3 1]
  [3 2 1]]

 [[4 1 3]
  [4 2 1]]

 [[3 2 1]
  [4 2 4]]]


In [18]:
x.ndim

3

In [19]:
x.shape # trzy tablice ,2 wiersze i trzy kolumny 

(3, 2, 3)

2. **Typy** **danych**

In [20]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [21]:
A = np.array([1.2,1.3,1.4])
A.dtype

dtype('float64')

In [22]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [23]:
A = np.array([1,2,3], dtype='complex')
A.dtype
print(A)

[1.+0.j 2.+0.j 3.+0.j]


In [24]:
A = np.array([1.2,2.3,1.4],dtype='int')
A.dtype
print(A)

[1 2 1]


In [25]:
A = np.array([True,False])
A.dtype

dtype('bool')

In [26]:
A = np.array([24,120,230], dtype=np.int8)
A.dtype

dtype('int8')

In [27]:
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

3.**Tworzenie** **Tablic**

In [28]:
np.zeros(shape=(4,10),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.full(shape=(3,3),fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [31]:
np.arange(start=2,stop=100,step=10,dtype='int')

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [32]:
np.arange(start=100,stop=10,step=-10,dtype='int')

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [33]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [34]:
np.linspace(start=0,stop=1,num=30)# num ile elementów równo rozłożónych chcemy miec z danego przedziału

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [35]:
A = np.arange(0,15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
A.reshape((3,5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
A.reshape((5,-1))# -1 samo wykrywa ile ma być kolumn 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

**4.Podstawowe operacji na tablicach **

In [38]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

In [39]:
A+B

array([6, 0, 7, 4])

In [40]:
A-B

array([0, 2, 1, 0])

In [41]:
A*B

array([ 9, -1, 12,  4])

In [42]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [43]:
np.add(A,B)

array([6, 0, 7, 4])

In [44]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [45]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [46]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [47]:
A+3 # dodaje nam 3 do kazdego elementu w tablicy 

array([6, 4, 7, 5])

In [48]:
2*A

array([6, 2, 8, 4])

In [49]:
A+ 3*B

array([12, -2, 13,  8])

In [50]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [51]:
# mnozenie macierzowe,
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [52]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [53]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [54]:
X @ Y  # '@' symbol do mnożenia macierzowego 

array([[  3,   6],
       [-12,   0]])

**5.Generowanie liczb pseudolosowych**

In [55]:
np.random.seed(0) # pozwala to losowanie ciągle tych samych liczb

np.random.randn()

1.764052345967664

In [56]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [57]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [58]:
# Rozkłąd jednostajny na przedziale
np.random.rand(10)

array([0.19658236, 0.36872517, 0.82099323, 0.09710128, 0.83794491,
       0.09609841, 0.97645947, 0.4686512 , 0.97676109, 0.60484552])

In [59]:
np.random.rand(10,2)

array([[0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212],
       [0.56660145, 0.26538949],
       [0.52324805, 0.09394051],
       [0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038],
       [0.13179786, 0.7163272 ]])

In [60]:
np.random.randint(10)# zwraca jedną wartość losową z jakiegoś przedzaiłu 

0

In [61]:
np.random.randint(low=10,high=101,size=5)

array([48, 29, 56, 52, 66])

In [62]:
np.random.choice([4,2,1,4]) # funkcja zwraca nam losowy element z listy 

4

In [63]:
np.random.choice(['python','java','SQL'])

'python'

In [64]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.random.shuffle(data) # shuffle zmiania kolejność w naszej tablicy 

In [66]:
data

array([4, 5, 0, 1, 7, 9, 6, 3, 2, 8])

**6.Podstawowe funkcje **

In [67]:
np.exp(1)

2.718281828459045

In [68]:
np.exp(2)

7.38905609893065

In [69]:
np.sqrt(7)# pierwiastek z liczby 

2.6457513110645907

In [70]:
np.all([2,3,0])# zwraca wartość TRUE jezeli wszystko jes prawdziwe jezelic cokolwiek jest False to zwraca False 

False

In [71]:
np.any([1,2,0])# zwraca wartość TRUE jezeli jedna wartośc jest prawdziwa

True

In [72]:
bool(0)

False

In [73]:
A = np.random.rand(5)
A

array([0.75610669, 0.39609828, 0.89603839, 0.63892108, 0.89155444])

In [74]:
np.argmax(A) # zwraca indeks gdzie wartość  jest największą 

2

In [75]:
A[np.argmax(A)]

0.896038387509077

In [76]:
np.argmin(A)

1

In [77]:
np.argsort(A)# sortuje wartości od najmniejsze do największej według indeksów 

array([1, 3, 0, 4, 2])

In [78]:
np.max(A)

0.896038387509077

In [79]:
np.min(A)

0.3960982754233623

In [80]:
np.mean(A)# liczy srednią 

0.7157437740508941

In [81]:
np.median(A)

0.7561066938650409

In [82]:
np.std(A)# odchylenie standardowe 

0.18607507835120637

**7.Indeksowanie i wycinanie **

In [83]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [84]:
# A[idx], A[start,stop], A[:stop], A[start:]

In [85]:
A[:13]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [86]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [87]:
A[[0,2]]

array([0, 2])

In [88]:
A[-1]

19

In [89]:
A[10:15]

array([10, 11, 12, 13, 14])

In [90]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
A[0]#wycina cały wiersz

array([0, 1, 2, 3, 4])

In [92]:
A[1]

array([5, 6, 7, 8, 9])

In [93]:
A[:,1]# wycina kolumne 

array([ 1,  6, 11, 16])

In [94]:
A[:,-1]

array([ 4,  9, 14, 19])

In [95]:
A[1,1]# wycinanie jednego elementu podajemy indeksy wiersza i kolumny 

6

In [96]:
A[1,3]

8

In [97]:
# wycinanie fragmentu 
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [98]:
A[1,2] =14 # zastepujemy wartość pod tym indeksem inną wartośca
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**8. Iteracja po tablicach **

In [101]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [102]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [103]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [106]:
A.shape

(4, 5)

In [107]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [108]:
A.ravel()# pozwala na powrót do postaci jednowymiarowej 

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [109]:
A.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

**Maski logiczne**

In [112]:
A = np.arange(-10,10,0.5)
A.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [114]:
A >0
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [116]:
np.bitwise_and(A>-5, A<5)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [117]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [118]:
np.bitwise_or(A<-5,A>5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [119]:
A[np.bitwise_or(A<-5,A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])